name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main   # Trigger only on pushes to main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # Uploads everything in repo (index.html must exist in root)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
